name: Build

on:
  [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
      fail-fast: false
    name: Build and test on JDK ${{ matrix.java }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run gradle
        run: ./gradlew jacocoTestReport publishToMavenLocal --no-daemon
      - name: Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: java-${{ matrix.java }}
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      continue-on-error: true
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
